version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - echo Entered the install phase
      - npm install npm@latest -g
      - pip install --upgrade pip
      - pip install --upgrade awscli
    finally:
      - echo Completed the install phase
  pre_build:
    commands:
      - echo Entered the pre_build phase
      - npm run build
    finally:
      - echo Completed the pre_build phase
  post_build:
    commands:
      - echo Entered the post_build phase
      - aws s3 sync ./dist $S3_BUCKET
    finally:
      - echo Completed the post_build phase


